name: environment-setup
inputs:
  version:
    required: true

runs:
  # Defining the action steps(Just one step to be simple)
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Python checks
    uses: actions/setup-python@v3
    with:
        python-version: ${{ inputs.version }}
  - name: Python environment setup
    shell: "bash"
    run: |
      python -m pip install --upgrade pip
      pip install poetry
      poetry install
